# BOW implementation

In [1]:
import pandas as pd
message = pd.read_csv('ham_spam_1000.csv',names=['label','message'])

In [2]:
message

label                                            message
0     label                                            message
1       ham            Can you help me with the math homework?
2      spam  Dear user, get rich quick with our crypto system!
3       ham  Your order has been shipped and will arrive soon.
4      spam         Free entry to the VIP club for today only.
...     ...                                                ...
996    spam  You’ve been chosen for a free cruise to the Ba...
997     ham            Can we reschedule our call to tomorrow?
998     ham         Happy birthday! Hope you have a great day.
999    spam  This message is from the IRS. Pay now or face ...
1000    ham                         I'll text you the address.

[1001 rows x 2 columns]

In [45]:
import re

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
# sn = SnowballStemmer('english')


In [46]:
corpus = []
for i in range(0,len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['messag',
 'help math homework',
 'dear user get rich quick crypto system',
 'order ship arriv soon',
 'free entri vip club today',
 'lunch new cafe',
 'claim free reward point',
 'pm',
 'messag ir pay face arrest',
 'congratul lucki winner ipad',
 'meet postpon pm',
 'exclus deal buy one get one free today',
 'lotteri claim',
 'hey still tonight',
 'forget submit assign',
 'help math homework',
 'earn money sleep start today',
 'dear user get rich quick crypto system',
 'lowest price medicin order without prescript',
 'happi birthday hope great day',
 'let finish project today',
 'act fast hour left claim prize',
 'exclus deal buy one get one free today',
 'congratul lucki winner ipad',
 'lowest price medicin order without prescript',
 'exclus deal buy one get one free today',
 'exclus deal buy one get one free today',
 'chosen free cruis bahama',
 'netflix account suspend login fix',
 'free entri vip club today',
 'act fast hour left claim prize',
 'lowest price medicin order withou

# Create Bag of Words

In [28]:
## creating bag of words model
from sklearn.feature_extraction.text import CountVectorizer
## for binary bow enable binary = True
cv = CountVectorizer(max_features=1000,binary=True)

In [29]:
x = cv.fit_transform(corpus).toarray()

In [30]:
x


array([[0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, ..., 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0]], shape=(1001, 135))

In [31]:
import numpy as np
np.set_printoptions(edgeitems=6, linewidth=1000, formatter=dict(float=lambda x: "%.3f" % x))
x

array([[0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, ..., 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0]], shape=(1001, 135))

# N-Gram

In [32]:
cv.vocabulary_

{'messag': np.int64(76),
 'help': np.int64(51),
 'math': np.int64(73),
 'homework': np.int64(54),
 'dear': np.int64(31),
 'user': np.int64(128),
 'get': np.int64(48),
 'rich': np.int64(100),
 'quick': np.int64(95),
 'crypto': np.int64(28),
 'system': np.int64(117),
 'order': np.int64(85),
 'ship': np.int64(104),
 'arriv': np.int64(7),
 'soon': np.int64(109),
 'free': np.int64(47),
 'entri': np.int64(38),
 'vip': np.int64(129),
 'club': np.int64(22),
 'today': np.int64(121),
 'lunch': np.int64(72),
 'new': np.int64(81),
 'cafe': np.int64(15),
 'claim': np.int64(20),
 'reward': np.int64(99),
 'point': np.int64(88),
 'pm': np.int64(87),
 'ir': np.int64(61),
 'pay': np.int64(86),
 'face': np.int64(40),
 'arrest': np.int64(6),
 'congratul': np.int64(24),
 'lucki': np.int64(71),
 'winner': np.int64(132),
 'ipad': np.int64(59),
 'meet': np.int64(75),
 'postpon': np.int64(89),
 'exclus': np.int64(39),
 'deal': np.int64(30),
 'buy': np.int64(14),
 'one': np.int64(84),
 'lotteri': np.int64(69),


In [39]:
## creating bag of words model with N-grams
from sklearn.feature_extraction.text import CountVectorizer
## for binary bow enable binary = True
cv = CountVectorizer(max_features=1000,binary=True, ngram_range=(1, 2))
x = cv.fit_transform(corpus).toarray()

In [40]:
cv.vocabulary_

{'messag': np.int64(151),
 'help': np.int64(103),
 'math': np.int64(144),
 'homework': np.int64(109),
 'help math': np.int64(104),
 'math homework': np.int64(145),
 'dear': np.int64(58),
 'user': np.int64(244),
 'get': np.int64(96),
 'rich': np.int64(199),
 'quick': np.int64(189),
 'crypto': np.int64(52),
 'system': np.int64(227),
 'dear user': np.int64(59),
 'user get': np.int64(245),
 'get rich': np.int64(98),
 'rich quick': np.int64(200),
 'quick crypto': np.int64(190),
 'crypto system': np.int64(53),
 'order': np.int64(171),
 'ship': np.int64(206),
 'arriv': np.int64(11),
 'soon': np.int64(214),
 'order ship': np.int64(172),
 'ship arriv': np.int64(207),
 'arriv soon': np.int64(12),
 'free': np.int64(90),
 'entri': np.int64(73),
 'vip': np.int64(246),
 'club': np.int64(41),
 'today': np.int64(234),
 'free entri': np.int64(92),
 'entri vip': np.int64(74),
 'vip club': np.int64(247),
 'club today': np.int64(42),
 'lunch': np.int64(142),
 'new': np.int64(162),
 'cafe': np.int64(25),
 

In [41]:
x

array([[0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, ..., 0, 0, 0, 0, 0, 0]], shape=(1001, 259))